Repository mmtk/mmtk-core, pull requests merged in 2020-11, with the labels that each got.

#159 Document top-level modules and VM interfaces
  .github/scripts/ci-doc.sh
  .github/workflows/pre-review-ci.yml
  .github/workflows/rustdoc.yml
  src/lib.rs
  src/mm/memory_manager.rs
  src/mmtk.rs
  src/plan/global.rs
  src/plan/mutator_context.rs
  src/plan/trace.rs
  src/plan/tracelocal.rs
  src/plan/transitive_closure.rs
  src/policy/mod.rs
  src/scheduler/mod.rs
  src/util/constants.rs
  src/util/macros.rs
  src/util/mod.rs
  src/vm/active_plan.rs
  src/vm/collection.rs
  src/vm/mod.rs
  src/vm/object_model.rs
  src/vm/reference_glue.rs
  src/vm/scanning.rs
  src/vm/unboxed_size_constants.rs
Labels: PR-benchmarking

#160 Update JikesRVM-related CI steps for removing mmtk-core submodule.
  .github/workflows/micro-bm.yml
  .github/workflows/perf-regression-ci.yml
  .github/workflows/post-review-ci.yml
  .github/workflows/stress-ci.yml
Labels: PR-benchmarking

#161 Rename enum Allocator to AllocationSemantic
  .github/workflows/micro-bm.yml
  .github/workflows/perf-regression-ci.yml
  .github/workflows/post-review-ci.yml
  src/lib.rs
  src/mm/memory_manager.rs
  src/plan/gencopy/gc_works.rs
  src/plan/gencopy/global.rs
  src/plan/gencopy/mutator.rs
  src/plan/global.rs
  src/plan/mod.rs
  src/plan/mutator_context.rs
  src/plan/nogc/global.rs
  src/plan/nogc/mutator.rs
  src/plan/semispace/gc_works.rs
  src/plan/semispace/global.rs
  src/plan/semispace/mutator.rs
  src/policy/copyspace.rs
  src/util/forwarding_word.rs
  src/vm/object_model.rs
  vmbindings/dummyvm/src/api.rs
  vmbindings/dummyvm/src/object_model.rs
  vmbindings/dummyvm/src/tests/issue139.rs
Labels: PR-benchmarking

#170 Include v8 tests in CI
  .github/workflows/micro-bm.yml
  .github/workflows/post-review-ci.yml
Labels: PR-testing

#174 Fix SFT map bugs
  src/policy/copyspace.rs
  src/policy/immortalspace.rs
  src/policy/largeobjectspace.rs
  src/policy/lockfreeimmortalspace.rs
  src/policy/space.rs
  src/util/conversions.rs
  src/util/heap/monotonepageresource.rs
Labels: PR-testing

#175 Fix deprecated set-env
  .github/workflows/micro-bm.yml
  .github/workflows/post-review-ci.yml
  .github/workflows/stress-ci.yml
Labels: PR-testing

#173 Object model cleanup
  src/util/forwarding_word.rs
  src/util/gc_byte.rs
  src/util/mod.rs
  src/vm/object_model.rs
  vmbindings/dummyvm/src/object_model.rs
Labels: PR-testing

#177 Use env-logger. Allow logger initialisation to fail.
  Cargo.toml
  src/mm/memory_manager.rs
  src/policy/space.rs
  src/util/logger.rs
Labels: PR-benchmarking, PR-testing

#176 object model cleanup - part 2
  src/plan/global.rs
  src/plan/semispace/gc_works.rs
  src/policy/immortalspace.rs
  src/policy/largeobjectspace.rs
  src/util/alloc/bumpallocator.rs
  src/util/forwarding_word.rs
  src/util/gc_byte.rs
  src/util/header_byte.rs
  src/vm/object_model.rs
  vmbindings/dummyvm/src/object_model.rs
Labels: PR-testing
