Repository mmtk/mmtk-core, pull requests merged in 2021-05, with the labels that each got.

#296 Mmap refactoring
  src/policy/lockfreeimmortalspace.rs
  src/util/address.rs
  src/util/heap/layout/byte_map_mmapper.rs
  src/util/heap/layout/fragmented_mapper.rs
  src/util/memory.rs
  src/util/raw_memory_freelist.rs
  src/util/side_metadata/global.rs
  src/util/side_metadata/helpers.rs
  src/util/side_metadata/helpers_32.rs
  src/util/test_util.rs
Labels: PR-testing

#304 Remove OOM lock
  src/plan/global.rs
  src/util/alloc/allocator.rs
Labels: PR-testing

#298 Side metadata page accounting
  docs/tutorial/code/mygc_semispace/global.rs
  src/plan/gencopy/global.rs
  src/plan/global.rs
  src/plan/marksweep/global.rs
  src/plan/nogc/global.rs
  src/plan/semispace/global.rs
  src/policy/copyspace.rs
  src/policy/immortalspace.rs
  src/policy/largeobjectspace.rs
  src/policy/lockfreeimmortalspace.rs
  src/policy/mallocspace/global.rs
  src/policy/mallocspace/metadata.rs
  src/policy/space.rs
  src/util/heap/accounting.rs
  src/util/heap/freelistpageresource.rs
  src/util/heap/layout/byte_map_mmapper.rs
  src/util/heap/layout/fragmented_mapper.rs
  src/util/heap/layout/mmapper.rs
  src/util/heap/mod.rs
  src/util/heap/monotonepageresource.rs
  src/util/heap/pageresource.rs
  src/util/side_metadata/global.rs
  src/util/side_metadata/helpers.rs
  src/util/side_metadata/helpers_32.rs
  src/util/side_metadata/mod.rs
  src/util/side_metadata/side_metadata_tests.rs
Labels: PR-benchmarking, PR-testing

#303 Change sft from pointers to static refs
  src/mmtk.rs
  src/policy/space.rs
Labels: PR-testing

#307 Handle mmap failure properly
  src/policy/space.rs
  src/util/heap/layout/byte_map_mmapper.rs
  src/util/heap/layout/fragmented_mapper.rs
  src/util/heap/layout/mmapper.rs
  src/util/memory.rs
  src/vm/collection.rs
  vmbindings/dummyvm/src/tests/handle_mmap_conflict.rs
  vmbindings/dummyvm/src/tests/handle_mmap_oom.rs
  vmbindings/dummyvm/src/tests/mod.rs
Labels: PR-testing

#306 Refactor TLS
  docs/tutorial/code/mygc_semispace/gc_work.rs
  docs/tutorial/code/mygc_semispace/global.rs
  docs/tutorial/code/mygc_semispace/mutator.rs
  src/mm/memory_manager.rs
  src/mmtk.rs
  src/plan/controller_collector_context.rs
  src/plan/gencopy/gc_work.rs
  src/plan/gencopy/global.rs
  src/plan/gencopy/mutator.rs
  src/plan/global.rs
  src/plan/marksweep/global.rs
  src/plan/marksweep/mutator.rs
  src/plan/mutator_context.rs
  src/plan/nogc/global.rs
  src/plan/nogc/mutator.rs
  src/plan/semispace/gc_work.rs
  src/plan/semispace/global.rs
  src/plan/semispace/mutator.rs
  src/policy/largeobjectspace.rs
  src/policy/lockfreeimmortalspace.rs
  src/policy/mallocspace/global.rs
  src/policy/space.rs
  src/scheduler/context.rs
  src/scheduler/mmtk_context.rs
  src/scheduler/scheduler.rs
  src/scheduler/worker.rs
  src/util/alloc/allocator.rs
  src/util/alloc/allocators.rs
  src/util/alloc/bumpallocator.rs
  src/util/alloc/large_object_allocator.rs
  src/util/alloc/malloc_allocator.rs
  src/util/finalizable_processor.rs
  src/util/heap/freelistpageresource.rs
  src/util/heap/monotonepageresource.rs
  src/util/heap/pageresource.rs
  src/util/memory.rs
  src/util/mod.rs
  src/util/opaque_pointer.rs
  src/util/reference_processor.rs
  src/vm/active_plan.rs
  src/vm/collection.rs
  src/vm/reference_glue.rs
  src/vm/scanning.rs
  tests/scheduler.rs
  vmbindings/dummyvm/src/active_plan.rs
  vmbindings/dummyvm/src/api.rs
  vmbindings/dummyvm/src/collection.rs
  vmbindings/dummyvm/src/reference_glue.rs
  vmbindings/dummyvm/src/scanning.rs
  vmbindings/dummyvm/src/tests/handle_mmap_conflict.rs
  vmbindings/dummyvm/src/tests/handle_mmap_oom.rs
  vmbindings/dummyvm/src/tests/issue139.rs
Labels: PR-testing

#311 Print out total time spent executing a type of work packet
  src/scheduler/stat.rs
Labels: PR-approved, PR-benchmarking, PR-ready-for-review, PR-testing

#312 Reduce public visibility
  .github/scripts/ci-doc.sh
  src/lib.rs
  src/memory_manager.rs
  src/mm/mod.rs
  src/mmtk.rs
  src/plan/barriers.rs
  src/plan/marksweep/mod.rs
  src/plan/mod.rs
  src/policy/copyspace.rs
  src/policy/immortalspace.rs
  src/policy/largeobjectspace.rs
  src/policy/lockfreeimmortalspace.rs
  src/policy/mallocspace/mod.rs
  src/policy/mod.rs
  src/policy/space.rs
  src/scheduler/gc_work.rs
  src/scheduler/mod.rs
  src/scheduler/scheduler.rs
  src/scheduler/work.rs
  src/scheduler/work_bucket.rs
  src/util/alloc/malloc_allocator.rs
  src/util/alloc/mod.rs
  src/util/constants.rs
  src/util/heap/layout/byte_map_mmapper.rs
  src/util/macros.rs
  src/util/mod.rs
  src/util/sanity/sanity_checker.rs
  src/util/side_metadata/mod.rs
  src/vm/object_model.rs
  src/vm/scanning.rs
  tests/scheduler.rs
  vmbindings/dummyvm/src/active_plan.rs
  vmbindings/dummyvm/src/collection.rs
  vmbindings/dummyvm/src/scanning.rs
Labels: PR-testing

#316 Rename initialize_header to initialize_object_metadata
  src/plan/mutator_context.rs
  src/policy/copyspace.rs
  src/policy/immortalspace.rs
  src/policy/largeobjectspace.rs
  src/policy/lockfreeimmortalspace.rs
  src/policy/mallocspace/global.rs
  src/policy/space.rs
Labels: PR-testing

#323 Rebase JikesRVM
  .github/workflows/micro-bm.yml
  .github/workflows/perf-jikesrvm-baseline.yml
  .github/workflows/perf-openjdk-baseline.yml
  .github/workflows/perf-regression-ci.yml
  .github/workflows/post-review-ci.yml
Labels: PR-benchmarking

#321 Update to Rust nightly 2021-05-12
  rust-toolchain
  src/lib.rs
  src/plan/controller_collector_context.rs
  src/plan/gencopy/gc_work.rs
  src/plan/semispace/gc_work.rs
  src/util/address.rs
  src/util/generic_freelist.rs
  src/util/heap/layout/fragmented_mapper.rs
  src/util/heap/layout/map32.rs
  src/util/int_array_freelist.rs
  src/util/memory.rs
  src/util/options.rs
  src/util/raw_memory_freelist.rs
  src/util/statistics/stats.rs
Labels: PR-testing

#332 Update to ci-perf-kit 0.6.2
  .github/workflows/micro-bm.yml
  .github/workflows/perf-jikesrvm-baseline.yml
  .github/workflows/perf-openjdk-baseline.yml
  .github/workflows/perf-regression-ci.yml
  .github/workflows/post-review-ci.yml
Labels: PR-benchmarking

#310 Side metadata consistency check
  docs/tutorial/code/mygc_semispace/gc_work.rs
  docs/tutorial/code/mygc_semispace/global.rs
  src/plan/gencopy/global.rs
  src/plan/global.rs
  src/plan/marksweep/global.rs
  src/plan/nogc/global.rs
  src/plan/semispace/global.rs
  src/policy/mallocspace/global.rs
  src/policy/space.rs
  src/util/heap/layout/byte_map_mmapper.rs
  src/util/heap/layout/fragmented_mapper.rs
  src/util/side_metadata/constants.rs
  src/util/side_metadata/global.rs
  src/util/side_metadata/mod.rs
  src/util/side_metadata/sanity.rs
  src/util/side_metadata/side_metadata_tests.rs
Labels: PR-testing
