Repository mmtk/mmtk-core, pull requests merged in 2021-06, with the labels that each got.

#338 Fix Gencopy full heap GC
  src/plan/gencopy/global.rs
  src/plan/global.rs
  src/scheduler/gc_work.rs
  src/util/finalizable_processor.rs
  src/util/options.rs
Labels: PR-benchmarking, PR-testing

#334 Use mmapper for side metadata
  src/lib.rs
  src/plan/gencopy/global.rs
  src/policy/copyspace.rs
  src/policy/lockfreeimmortalspace.rs
  src/policy/mallocspace/global.rs
  src/policy/space.rs
  src/util/heap/layout/byte_map_mmapper.rs
  src/util/heap/layout/fragmented_mapper.rs
  src/util/heap/layout/mmapper.rs
  src/util/side_metadata/global.rs
  src/util/side_metadata/helpers.rs
  src/util/side_metadata/helpers_32.rs
Labels: PR-testing

#343 Support String options
  src/util/options.rs
Labels: PR-testing

#344 Update to ci-perf-kit 0.6.4
  .github/workflows/micro-bm.yml
  .github/workflows/perf-jikesrvm-baseline.yml
  .github/workflows/perf-openjdk-baseline.yml
  .github/workflows/perf-regression-ci.yml
  .github/workflows/post-review-ci.yml
Labels: PR-benchmarking, PR-testing

#347 Use -1 as uninitialized value for highwater_mark in FreeListPageResource
  src/util/heap/freelistpageresource.rs
Labels: PR-benchmarking, PR-testing

#342 Refactor Metadata
  Cargo.toml
  docs/tutorial/code/mygc_semispace/gc_work.rs
  docs/tutorial/code/mygc_semispace/global.rs
  src/memory_manager.rs
  src/plan/barriers.rs
  src/plan/gencopy/gc_work.rs
  src/plan/gencopy/global.rs
  src/plan/gencopy/mod.rs
  src/plan/gencopy/mutator.rs
  src/plan/global.rs
  src/plan/marksweep/global.rs
  src/plan/nogc/global.rs
  src/plan/plan_constraints.rs
  src/plan/semispace/gc_work.rs
  src/plan/semispace/global.rs
  src/policy/copyspace.rs
  src/policy/immortalspace.rs
  src/policy/largeobjectspace.rs
  src/policy/lockfreeimmortalspace.rs
  src/policy/mallocspace/global.rs
  src/policy/mallocspace/metadata.rs
  src/policy/space.rs
  src/scheduler/gc_work.rs
  src/util/forwarding_word.rs
  src/util/gc_byte.rs
  src/util/header_byte.rs
  src/util/metadata/global.rs
  src/util/metadata/header_metadata.rs
  src/util/metadata/mod.rs
  src/util/metadata/side_metadata/constants.rs
  src/util/metadata/side_metadata/global.rs
  src/util/metadata/side_metadata/helpers.rs
  src/util/metadata/side_metadata/helpers_32.rs
  src/util/metadata/side_metadata/mod.rs
  src/util/metadata/side_metadata/sanity.rs
  src/util/metadata/side_metadata/side_metadata_tests.rs
  src/util/mod.rs
  src/util/object_forwarding.rs
  src/vm/object_model.rs
  vmbindings/dummyvm/src/object_model.rs
Labels: PR-benchmarking

#315 Add perf event support
  .github/scripts/ci-build.sh
  .github/scripts/ci-common.sh
  .github/scripts/ci-style.sh
  .github/scripts/ci-test.sh
  Cargo.toml
  src/scheduler/mod.rs
  src/scheduler/scheduler.rs
  src/scheduler/stat.rs
  src/scheduler/work.rs
  src/scheduler/work_counter.rs
  src/scheduler/worker.rs
  src/util/options.rs
  src/util/statistics/stats.rs
Labels: PR-testing

#345 PageProtect GC
  src/plan/global.rs
  src/plan/mod.rs
  src/plan/pageprotect/gc_work.rs
  src/plan/pageprotect/global.rs
  src/plan/pageprotect/mod.rs
  src/plan/pageprotect/mutator.rs
  src/policy/largeobjectspace.rs
  src/policy/mallocspace/metadata.rs
  src/util/heap/freelistpageresource.rs
  src/util/heap/layout/vm_layout_constants.rs
  src/util/metadata/side_metadata/constants.rs
  src/util/options.rs
  src/util/treadmill.rs
Labels: PR-benchmarking
