Repository mmtk/mmtk-core, pull requests merged in 2021-08, with the labels that each got.

#392 Run binding tests with extreme_assertions
  .github/workflows/post-review-ci.yml
  docs/tutorial/code/mygc_semispace/global.rs
  src/memory_manager.rs
  src/plan/gencopy/global.rs
  src/plan/global.rs
  src/plan/marksweep/global.rs
  src/plan/nogc/global.rs
  src/plan/pageprotect/global.rs
  src/plan/plan_constraints.rs
  src/plan/semispace/global.rs
  src/scheduler/gc_work.rs
  src/util/edge_logger.rs
Labels: PR-testing

#401 Fix the concurrency issue for munprotect for PageProtect
  src/util/heap/freelistpageresource.rs
Labels: PR-testing

#404 Fix a concurrency bug in mapping chunk side metadata for mallocspace
  src/policy/mallocspace/global.rs
  src/policy/mallocspace/metadata.rs
Labels: PR-testing

#382 Add Immix GC
  src/lib.rs
  src/mmtk.rs
  src/plan/global.rs
  src/plan/immix/gc_work.rs
  src/plan/immix/global.rs
  src/plan/immix/mod.rs
  src/plan/immix/mutator.rs
  src/plan/mod.rs
  src/plan/transitive_closure.rs
  src/policy/immix/block.rs
  src/policy/immix/chunk.rs
  src/policy/immix/defrag.rs
  src/policy/immix/immixspace.rs
  src/policy/immix/line.rs
  src/policy/immix/mod.rs
  src/policy/mod.rs
  src/util/alloc/allocators.rs
  src/util/alloc/immix_allocator.rs
  src/util/alloc/mod.rs
  src/util/metadata/side_metadata/constants.rs
  src/util/metadata/side_metadata/global.rs
  src/util/metadata/side_metadata/helpers_32.rs
  src/util/options.rs
  vmbindings/dummyvm/src/api.rs
Labels: PR-testing

#411 Fix a random local side metadata not mapped bug
  src/util/metadata/side_metadata/helpers_32.rs
Labels: PR-testing

#410 Upgrade to Rust nightly-2021-08-10
  rust-toolchain
  src/lib.rs
  src/plan/gencopy/global.rs
  src/plan/immix/global.rs
  src/plan/marksweep/global.rs
  src/plan/nogc/global.rs
  src/plan/pageprotect/global.rs
  src/plan/semispace/global.rs
  src/policy/immix/block.rs
  src/policy/immix/chunk.rs
  src/policy/immix/line.rs
  src/policy/space.rs
  src/scheduler/scheduler.rs
  src/util/heap/layout/fragmented_mapper.rs
  src/util/heap/vmrequest.rs
  src/util/metadata/log_bit.rs
  src/util/metadata/side_metadata/global.rs
  src/util/metadata/side_metadata/sanity.rs
Labels: PR-testing

#390 Global allocation bit
  Cargo.toml
  src/plan/immix/global.rs
  src/plan/marksweep/global.rs
  src/policy/copyspace.rs
  src/policy/immix/block.rs
  src/policy/immix/immixspace.rs
  src/policy/immortalspace.rs
  src/policy/largeobjectspace.rs
  src/policy/lockfreeimmortalspace.rs
  src/policy/mallocspace/global.rs
  src/policy/mallocspace/metadata.rs
  src/util/alloc/immix_allocator.rs
  src/util/alloc_bit.rs
  src/util/heap/monotonepageresource.rs
  src/util/metadata/side_metadata/constants.rs
  src/util/metadata/side_metadata/global.rs
  src/util/mod.rs
  src/util/object_forwarding.rs
Labels: PR-testing

#417 Check bounds of active chunk metadata spec in is_chunk_mapped
  src/policy/mallocspace/metadata.rs
  src/util/metadata/side_metadata/constants.rs
Labels: PR-testing

#418 Rename phase-based counters
  .github/workflows/micro-bm.yml
  .github/workflows/perf-jikesrvm-baseline.yml
  .github/workflows/perf-openjdk-baseline.yml
  .github/workflows/perf-regression-ci.yml
  .github/workflows/post-review-ci.yml
  src/util/statistics/stats.rs
Labels: A-utils

#413 Fix object logging code
  src/plan/barriers.rs
Labels: PR-benchmarking, PR-testing
