Repository mmtk/mmtk-core, pull requests merged in 2021-03, with the labels that each got.

#184 Side-metadata supported object remembering barrier
  src/plan/barriers.rs
  src/plan/gencopy/gc_work.rs
  src/plan/gencopy/global.rs
  src/plan/gencopy/mod.rs
  src/plan/gencopy/mutator.rs
  src/plan/mutator_context.rs
  src/policy/space.rs
  src/scheduler/gc_work.rs
  src/util/heap/freelistpageresource.rs
  src/util/heap/layout/byte_map_mmapper.rs
  src/util/heap/layout/fragmented_mapper.rs
  src/util/heap/layout/mmapper.rs
  src/util/heap/layout/vm_layout_constants.rs
  src/util/heap/monotonepageresource.rs
  src/util/side_metadata/global.rs
Labels: PR-testing

#259 Marksweep
  .github/scripts/ci-test.sh
  .github/workflows/post-review-ci.yml
  src/mm/memory_manager.rs
  src/plan/global.rs
  src/plan/marksweep/gc_work.rs
  src/plan/marksweep/global.rs
  src/plan/marksweep/mod.rs
  src/plan/marksweep/mutator.rs
  src/plan/mod.rs
  src/policy/mallocspace/global.rs
  src/policy/mallocspace/metadata.rs
  src/policy/mallocspace/mod.rs
  src/policy/mod.rs
  src/policy/space.rs
  src/scheduler/gc_work.rs
  src/scheduler/work.rs
  src/util/address.rs
  src/util/alloc/allocators.rs
  src/util/alloc/malloc_allocator.rs
  src/util/alloc/mod.rs
  src/util/constants.rs
  src/util/gc_byte.rs
  src/util/options.rs
  src/util/side_metadata/constants.rs
  src/util/side_metadata/global.rs
  src/util/side_metadata/mod.rs
Labels: PR-benchmarking, PR-testing

#263 GenCopy perf CI
  .github/workflows/micro-bm.yml
  .github/workflows/perf-regression-ci.yml
  .github/workflows/post-review-ci.yml
Labels: PR-benchmarking

#264 Side metadata performance regression
  Cargo.toml
  docs/tutorial/code/mygc_semispace/global.rs
  docs/tutorial/src/mygc/ss/exercise_solution.md
  src/plan/gencopy/global.rs
  src/plan/gencopy/mod.rs
  src/plan/global.rs
  src/plan/marksweep/global.rs
  src/plan/semispace/global.rs
  src/policy/lockfreeimmortalspace.rs
  src/policy/mallocspace/metadata.rs
  src/policy/mod.rs
  src/policy/space.rs
  src/util/forwarding_word.rs
  src/util/gc_byte.rs
  src/util/heap/freelistpageresource.rs
  src/util/heap/layout/byte_map_mmapper.rs
  src/util/heap/layout/fragmented_mapper.rs
  src/util/heap/layout/mmapper.rs
  src/util/heap/monotonepageresource.rs
  src/util/memory.rs
  src/util/side_metadata/constants.rs
  src/util/side_metadata/global.rs
  src/util/side_metadata/helpers.rs
  src/util/side_metadata/helpers_32.rs
  src/util/side_metadata/mod.rs
  src/util/side_metadata/side_metadata_tests.rs
  src/vm/object_model.rs
  vmbindings/dummyvm/src/object_model.rs
Labels: PR-testing
